#!/usr/bin/env python3
"""Generate runtime/src/story/native_api_names.cpp from the extracted native API list
(docs/native-api.md, produced by lua_reg_scan.py + DecompileRefsTo.java).

The player uses the table to answer lookups of original native functions it does not implement
yet with a logging no-op (and plain nil for names the original never had).

Usage: gen_api_names.py docs/native-api.md runtime/src/story/native_api_names.cpp
"""
import re
import sys


def main(src, dst):
    types = []
    cur = None
    for line in open(src, encoding="utf-8"):
        m = re.match(r"^### (\w+)\s+\(luaL_Reg", line)
        if m:
            cur = [m.group(1), []]
            types.append(cur)
            continue
        if cur and line.startswith("  ") and not line.startswith("  #"):
            cur[1] += [n.strip() for n in line.split(",") if n.strip()]
            continue
        cur = None
    out = ["// Generated by tools/gen_api_names.py from docs/native-api.md - do not edit.",
           '#include "story/native_api_names.h"', "", "namespace oyster::story {", "",
           "const NativeTypeNames kNativeApiNames[] = {"]
    for name, funcs in types:
        out.append(f'    {{"{name}", "{" ".join(funcs)}"}},')
    out += ["    {nullptr, nullptr},", "};", "", "}  // namespace oyster::story", ""]
    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    print(f"{len(types)} types, {sum(len(f) for _, f in types)} functions")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
